config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  resources :users, only: [:index, :show, :create, :update, :destroy] do
    resources :transactions, only: [:index, :create]
    resources :rewards, only: [:index, :create]
  end

  resources :transactions, only: [:show, :update, :destroy]

  resources :rewards, only: [:show, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :transactions
    has_many :rewards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
    before_action :set_user
    before_action :set_reward, only: [:show, :edit, :update, :destroy]
  
    def index
      @rewards = @user.rewards
    end
  
    def show
    end
  
    def new
      @reward = @user.rewards.new
    end
  
    def edit
    end
  
    def create
      @reward = @user.rewards.new(reward_params)
      if @reward.save
        redirect_to user_rewards_path(@user), notice: 'Reward was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @reward.update(reward_params)
        redirect_to user_rewards_path(@user), notice: 'Reward was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @reward.destroy
      redirect_to user_rewards_path(@user), notice: 'Reward was successfully destroyed.'
    end
  
    private
      def set_user
        @user = User.find(params[:user_id])
      end
  
      def set_reward
        @reward = @user.rewards.find(params[:id])
      end
  
      def reward_params
        params.require(:reward).permit(:name, :valid_until, :user_id)
      end
  end
  

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
    before_action :set_user
    before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  
    def index
      @transactions = @user.transactions
    end
  
    def show
    end
  
    def new
      @transaction = @user.transactions.new
    end
  
    def edit
    end
  
    def create
      @transaction = @user.transactions.new(transaction_params)
      if @transaction.save
        redirect_to user_transactions_path(@user), notice: 'Transaction was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @transaction.update(transaction_params)
        redirect_to user_transactions_path(@user), notice: 'Transaction was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @transaction.destroy
      redirect_to user_transactions_path(@user), notice: 'Transaction was successfully destroyed.'
    end
  
    private
      def set_user
        @user = User.find(params[:user_id])
      end
  
      def set_transaction
        @transaction = @user.transactions.find(params[:id])
      end
  
      def transaction_params
        params.require(:transaction).permit(:amount, :user_id, :country)
      end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
  
    def index
      @users = User.all
    end
  
    def show
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to @user, notice: 'User was successfully created.'
      else
        render :new
      end
    end
  
    def update
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully updated.'
      else
        render :edit
      end
    end
  
    def destroy
      @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.'
    end
  
    private
      def set_user
        @user = User.find(params[:id])
      end
  
      def user_params
        params.require(:user).permit(:name, :email, :birthday, :loyalty_points, :last_cycle_points, :current_cycle_points)
      end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoyaltyProgram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rewards/_form.html.erb
<%= form_with(model: [@user, @reward], local: true) do |form| %>
    <% if @reward.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>
  
        <ul>
          <% @reward.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
  

app/views/rewards/edit.html.erb
<h1>Edit Reward</h1>

<%= render 'form' %>

<%= link_to 'Show', user_reward_path(@user, @reward) %> |
<%= link_to 'Back', user_rewards_path(@user) %>

app/views/rewards/index.html.erb
<h1>Rewards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.name %></td>
        <td><%= reward.description %></td>
        <td><%= link_to 'Show', user_reward_path(@user, reward) %></td>
        <td><%= link_to 'Edit', edit_user_reward_path(@user, reward) %></td>
        <td><%= link_to 'Destroy', [reward.user, reward], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_user_reward_path(@user) %>

app/views/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form' %>

<%= link_to 'Back', user_rewards_path(@user) %>

app/views/rewards/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @reward.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @reward.description %>
</p>

<%= link_to 'Edit', edit_user_reward_path(@user, @reward) %> |
<%= link_to 'Back', user_rewards_path(@user) %>

app/views/transactions/_form.html.erb
<%= form_with(model: [@user, @transaction], local: true) do |form| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
  
        <ul>
          <% @transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :amount %>
      <%= form.number_field :amount %>
    </div>
  
    <div class="field">
      <%= form.label :currency %>
      <%= form.text_field :currency %>
    </div>
  
    <div class="field">
      <%= form.label :country %>
      <%= form.text_field :country %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>
  

app/views/transactions/edit.html.erb
<h1>Edit Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', user_transaction_path(@user, @transaction) %> |
<%= link_to 'Back', user_transactions_path(@user) %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Currency</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.amount %></td>
        <td><%= transaction.currency %></td>
        <td><%= transaction.country %></td>
        <td><%= link_to 'Show', user_transaction_path(@user, transaction) %></td>
        <td><%= link_to 'Edit', edit_user_transaction_path(@user, transaction) %></td>
        <td><%= link_to 'Destroy', [transaction.user, transaction], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_user_transaction_path(@user) %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', user_transactions_path(@user) %>

app/views/transactions/show.html.erb
<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @transaction.currency %>
</p>

<p>
  <strong>Country:</strong>
  <%= @transaction.country %>
</p>

<%= link_to 'Edit', edit_user_transaction_path(@user, @transaction) %> |
<%= link_to 'Back', user_transactions_path(@user) %>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'New Transaction', new_user_transaction_path(user) %></td>
        <td><%= link_to 'Destroy', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>